### ISSUE TITLE
Use case 13: Edit a To-Do List name.

### ISSUE THREAD

**Issue by VRushLP** [VRushLP/DoItApp#16]
Actor: App user
Preconditions: User is logged in and at their station.
Successful Condition: To-Do List name is changed to reflect the edit. 
Main Scenario:
User holds down their finger on the list they want to edit to bring up the context menu.
User selects the “Edit List Name” option.
User is prompted for a new name via pop-up.
They can either cancel the dialog or enter a new name.
The list is updated to reflect any changes.

**Comment by Heyther** [comment]
Moved dialog creation and successfully works now
